import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors mb-10"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <h1 className="font-display text-4xl md:text-5xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground text-sm mb-12">Last updated: March 24, 2026</p>

        <div className="space-y-10 font-body text-sm text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">1. Agreement to Terms</h2>
            <p>
              By accessing or using the Xiilio.ai website, mobile application, and services
              (collectively, the "Service"), you agree to be bound by these Terms of Service
              ("Terms"). If you do not agree to these Terms, you may not access or use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p>
              Xiilio.ai provides AI-powered marketing and growth systems, including but not limited to
              AI voice agents, CRM automation, lead generation, and digital marketing services. We
              reserve the right to modify, suspend, or discontinue any part of the Service at any time
              without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">3. Eligibility</h2>
            <p>
              You must be at least 16 years of age to use the Service. By using the Service, you
              represent and warrant that you meet this age requirement and have the legal capacity to
              enter into these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">4. User Accounts</h2>
            <p>
              Certain features of the Service may require you to create an account. You are responsible
              for maintaining the confidentiality of your account credentials and for all activities
              that occur under your account. You agree to notify us immediately of any unauthorized use
              of your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">5. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Transmit any malware, viruses, or harmful code</li>
              <li>Use the Service to send unsolicited communications (spam)</li>
              <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
              <li>Impersonate any person or entity, or misrepresent your affiliation</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">6. AI Voice Agent (Aria)</h2>
            <p>
              The Service includes an AI-powered voice agent named Aria. By interacting with Aria, you
              acknowledge that responses are generated by artificial intelligence and may not always be
              accurate. Aria is not a substitute for professional advice. Any bookings or commitments
              made through Aria are subject to confirmation by our team.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">7. Intellectual Property</h2>
            <p>
              All content, features, and functionality of the Service — including but not limited to
              text, graphics, logos, icons, images, audio, video, software, and code — are the
              exclusive property of Xiilio.ai or its licensors and are protected by copyright,
              trademark, and other intellectual property laws. You may not reproduce, distribute,
              modify, or create derivative works without our prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">8. Third-Party Services</h2>
            <p>
              The Service may contain links to or integrations with third-party websites, services, or
              content. We are not responsible for the availability, accuracy, or practices of any
              third-party services. Your use of third-party services is at your own risk and subject to
              their respective terms and policies.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">9. Disclaimer of Warranties</h2>
            <p>
              The Service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any
              kind, whether express or implied, including but not limited to implied warranties of
              merchantability, fitness for a particular purpose, and non-infringement. We do not
              warrant that the Service will be uninterrupted, error-free, or secure.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Xiilio.ai and its officers, directors, employees,
              and agents shall not be liable for any indirect, incidental, special, consequential, or
              punitive damages, including but not limited to loss of profits, data, or goodwill,
              arising out of or in connection with your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">11. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Xiilio.ai and its affiliates from any claims,
              damages, losses, liabilities, and expenses (including legal fees) arising out of your use
              of the Service or violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">12. Termination</h2>
            <p>
              We may terminate or suspend your access to the Service at any time, without prior notice,
              for any reason, including breach of these Terms. Upon termination, your right to use the
              Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">13. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of England and
              Wales, without regard to its conflict of law provisions. Any disputes arising under these
              Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">14. Changes to These Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Changes will be posted on this
              page with an updated "Last updated" date. Your continued use of the Service after changes
              are posted constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">15. Contact Us</h2>
            <p>
              If you have questions about these Terms of Service, please contact us at:
            </p>
            <p className="mt-2 text-foreground">
              Xiilio.ai<br />
              Email:{" "}
              <a href="mailto:letsgo@xiilio.ai" className="text-primary hover:underline">
                letsgo@xiilio.ai
              </a>
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-border text-center">
          <p className="text-xs text-muted-foreground">© 2026 Xiilio.ai. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
